const simple_dropdown_controller={
    template:
    ` <dropdown-root
        :data="data"
        :tag="tag"
        :selected="select_change"
        @change_dropdown_value="change_drop"
      >
     </dropdown-root>`,
     data(){
        return{
            select_change:this.selected
        }
     },
     watch:{
        selected(){
            this.select_change = this.selected;
        }
     },
     props:{
        data:{
            type:Array
        },
        tag:{
            type:String,
            default:'_'
        },
        root_ref:{
            type:[Object,Boolean],
            default:false
        },
        root_event:{
            type:[Object,Boolean],
            default:false
        },
        selected:{
            type:[String,Number]
        },
        value:{
            type:[String,Number],
            default:0
        }
     },
     methods:{
        change_drop(data){
            this.$emit('change',data);
        }
     }
     
}